requirements.txt Remove version for python version
To avoid error like:

  ERROR: Cannot install zipp==3.20.2 because these package versions have conflicting dependencies.
  The conflict is caused by:
      The user requested zipp==3.20.2
      The user requested (constraint) zipp==3.21.0